### ISSUE TITLE
Làm sao để add các module kèm theo?

### ISSUE THREAD

**Issue by pdnguyen179** [KhanhNguyen9872/Cpycompile#1]
Làm sao để thêm các module .py kèm theo và thêm các thư mục trong project vào để compile ạ?

**Comment by KhanhNguyen9872** [comment]
> Làm sao để thêm các module .py kèm theo và thêm các thư mục trong project vào để compile ạ?

Tool này chỉ compile 1 file .py lẻ thôi bạn nhé, bạn nên compile file main của bạn, các file module .py còn lại và thư mục của bạn cứ để gần file đã compile vẫn chạy đc nhé

**Comment by pdnguyen179** [comment]
> > Làm sao để thêm các module .py kèm theo và thêm các thư mục trong project vào để compile ạ?
> 
> Tool này chỉ compile 1 file .py lẻ thôi bạn nhé, bạn nên compile file main của bạn, các file module .py còn lại và thư mục của bạn cứ để gần file đã compile vẫn chạy đc nhé
> 

E cám ơn ạ! Bác phát triển compile full project nuôn đi, xịn phết! :3

**Comment by KhanhNguyen9872** [comment]
> > > Làm sao để thêm các module .py kèm theo và thêm các thư mục trong project vào để compile ạ?
> > 
> > 
> > Tool này chỉ compile 1 file .py lẻ thôi bạn nhé, bạn nên compile file main của bạn, các file module .py còn lại và thư mục của bạn cứ để gần file đã compile vẫn chạy đc nhé
> 
> E cám ơn ạ! Bác phát triển compile full project nuôn đi, xịn phết! :3

đảm bảo k lộ đc code của bạn sau khi compile exe đâu, nhưng mà làm full project thì giờ chưa phải lúc
